/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC1271 } from "./IERC1271";
export type { IERC2981 } from "./IERC2981";
export type { IERC5267 } from "./IERC5267";
