/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { RunnerCharacter } from "./RunnerCharacter";
export type { RunnerSkin } from "./RunnerSkin";
export type { RunnerToken } from "./RunnerToken";
