/*
 * Indexer Search API
 *
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * The version of the OpenAPI document: 1.0
 * Contact: helpmebuild@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Search.Client.OpenAPIDateConverter;

namespace Immutable.Search.Model
{
    /// <summary>
    /// APIError400AllOf
    /// </summary>
    [DataContract(Name = "APIError400_allOf")]
    public partial class APIError400AllOf
    {
        /// <summary>
        /// Error Code
        /// </summary>
        /// <value>Error Code</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CodeEnum
        {
            /// <summary>
            /// Enum VALIDATIONERROR for value: VALIDATION_ERROR
            /// </summary>
            [EnumMember(Value = "VALIDATION_ERROR")]
            VALIDATIONERROR = 1
        }


        /// <summary>
        /// Error Code
        /// </summary>
        /// <value>Error Code</value>
        /// <example>VALIDATION_ERROR</example>
        [DataMember(Name = "code", IsRequired = true, EmitDefaultValue = true)]
        public CodeEnum Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="APIError400AllOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected APIError400AllOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="APIError400AllOf" /> class.
        /// </summary>
        /// <param name="code">Error Code (required).</param>
        /// <param name="details">Additional details to help resolve the error (required).</param>
        public APIError400AllOf(CodeEnum code = default(CodeEnum), Object details = default(Object))
        {
            this.Code = code;
            // to ensure "details" is required (not null)
            if (details == null)
            {
                throw new ArgumentNullException("details is a required property for APIError400AllOf and cannot be null");
            }
            this.Details = details;
        }

        /// <summary>
        /// Additional details to help resolve the error
        /// </summary>
        /// <value>Additional details to help resolve the error</value>
        [DataMember(Name = "details", IsRequired = true, EmitDefaultValue = true)]
        public Object Details { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class APIError400AllOf {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Details: ").Append(Details).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
