/*
 * Indexer Search API
 *
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * The version of the OpenAPI document: 1.0
 * Contact: helpmebuild@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Search.Model
{
    /// <summary>
    ///     BasicAPIError
    /// </summary>
    [DataContract(Name = "BasicAPIError")]
    public class BasicAPIError
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="BasicAPIError" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BasicAPIError()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="BasicAPIError" /> class.
        /// </summary>
        /// <param name="message">Error Message (required).</param>
        /// <param name="link">Link to IMX documentation that can help resolve this error (required).</param>
        /// <param name="traceId">Trace ID of the initial request (required).</param>
        public BasicAPIError(string message = default, string link = default, string traceId = default)
        {
            // to ensure "message" is required (not null)
            if (message == null)
                throw new ArgumentNullException("message is a required property for BasicAPIError and cannot be null");
            Message = message;
            // to ensure "link" is required (not null)
            if (link == null)
                throw new ArgumentNullException("link is a required property for BasicAPIError and cannot be null");
            Link = link;
            // to ensure "traceId" is required (not null)
            if (traceId == null)
                throw new ArgumentNullException("traceId is a required property for BasicAPIError and cannot be null");
            TraceId = traceId;
        }

        /// <summary>
        ///     Error Message
        /// </summary>
        /// <value>Error Message</value>
        /// <example>all fields must be provided</example>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        ///     Link to IMX documentation that can help resolve this error
        /// </summary>
        /// <value>Link to IMX documentation that can help resolve this error</value>
        /// <example>https://docs.x.immutable.com/reference/#/</example>
        [DataMember(Name = "link", IsRequired = true, EmitDefaultValue = true)]
        public string Link { get; set; }

        /// <summary>
        ///     Trace ID of the initial request
        /// </summary>
        /// <value>Trace ID of the initial request</value>
        /// <example>e47634b79a5cd6894ddc9639ec4aad26</example>
        [DataMember(Name = "trace_id", IsRequired = true, EmitDefaultValue = true)]
        public string TraceId { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BasicAPIError {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Link: ").Append(Link).Append("\n");
            sb.Append("  TraceId: ").Append(TraceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}