/*
 * Indexer Search API
 *
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * The version of the OpenAPI document: 1.0
 * Contact: helpmebuild@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Immutable.Search.Model
{
    /// <summary>
    ///     The metadata trait value
    /// </summary>
    [JsonConverter(typeof(NFTMetadataAttributeValueJsonConverter))]
    [DataContract(Name = "NFTMetadataAttribute_value")]
    public class NFTMetadataAttributeValue : AbstractOpenAPISchema
    {
        private object _actualInstance;

        /// <summary>
        ///     Initializes a new instance of the <see cref="NFTMetadataAttributeValue" /> class
        ///     with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public NFTMetadataAttributeValue(string actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="NFTMetadataAttributeValue" /> class
        ///     with the <see cref="decimal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of decimal.</param>
        public NFTMetadataAttributeValue(decimal actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance;
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="NFTMetadataAttributeValue" /> class
        ///     with the <see cref="bool" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of bool.</param>
        public NFTMetadataAttributeValue(bool actualInstance)
        {
            IsNullable = false;
            SchemaType = "oneOf";
            ActualInstance = actualInstance;
        }

        /// <summary>
        ///     Gets or Sets ActualInstance
        /// </summary>
        public override object ActualInstance
        {
            get => _actualInstance;
            set
            {
                if (value.GetType() == typeof(bool) || value is bool)
                    _actualInstance = value;
                else if (value.GetType() == typeof(decimal) || value is decimal)
                    _actualInstance = value;
                else if (value.GetType() == typeof(string) || value is string)
                    _actualInstance = value;
                else
                    throw new ArgumentException(
                        "Invalid instance found. Must be the following types: bool, decimal, string");
            }
        }

        /// <summary>
        ///     Get the actual instance of `string`. If the actual instance is not `string`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)ActualInstance;
        }

        /// <summary>
        ///     Get the actual instance of `decimal`. If the actual instance is not `decimal`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of decimal</returns>
        public decimal GetDecimal()
        {
            return (decimal)ActualInstance;
        }

        /// <summary>
        ///     Get the actual instance of `bool`. If the actual instance is not `bool`,
        ///     the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of bool</returns>
        public bool GetBool()
        {
            return (bool)ActualInstance;
        }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NFTMetadataAttributeValue {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, SerializerSettings);
        }

        /// <summary>
        ///     Converts the JSON string into an instance of NFTMetadataAttributeValue
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of NFTMetadataAttributeValue</returns>
        public static NFTMetadataAttributeValue FromJson(string jsonString)
        {
            NFTMetadataAttributeValue newNFTMetadataAttributeValue = null;

            if (string.IsNullOrEmpty(jsonString)) return newNFTMetadataAttributeValue;
            var match = 0;
            var matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(bool).GetProperty("AdditionalProperties") == null)
                    newNFTMetadataAttributeValue =
                        new NFTMetadataAttributeValue(
                            JsonConvert.DeserializeObject<bool>(jsonString, SerializerSettings));
                else
                    newNFTMetadataAttributeValue = new NFTMetadataAttributeValue(
                        JsonConvert.DeserializeObject<bool>(jsonString, AdditionalPropertiesSerializerSettings));
                matchedTypes.Add("bool");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into bool: {1}", jsonString, exception);
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(decimal).GetProperty("AdditionalProperties") == null)
                    newNFTMetadataAttributeValue =
                        new NFTMetadataAttributeValue(
                            JsonConvert.DeserializeObject<decimal>(jsonString, SerializerSettings));
                else
                    newNFTMetadataAttributeValue = new NFTMetadataAttributeValue(
                        JsonConvert.DeserializeObject<decimal>(jsonString, AdditionalPropertiesSerializerSettings));
                matchedTypes.Add("decimal");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into decimal: {1}", jsonString, exception);
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                    newNFTMetadataAttributeValue =
                        new NFTMetadataAttributeValue(
                            JsonConvert.DeserializeObject<string>(jsonString, SerializerSettings));
                else
                    newNFTMetadataAttributeValue = new NFTMetadataAttributeValue(
                        JsonConvert.DeserializeObject<string>(jsonString, AdditionalPropertiesSerializerSettings));
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                Debug.WriteLine("Failed to deserialize `{0}` into string: {1}", jsonString, exception);
            }

            if (match == 0)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` cannot be deserialized into any schema defined.");
            if (match > 1)
                throw new InvalidDataException("The JSON string `" + jsonString +
                                               "` incorrectly matches more than one schema (should be exactly one match): " +
                                               string.Join(",", matchedTypes));

            // deserialization is considered successful at this point if no exception has been thrown.
            return newNFTMetadataAttributeValue;
        }
    }

    /// <summary>
    ///     Custom JSON converter for NFTMetadataAttributeValue
    /// </summary>
    public class NFTMetadataAttributeValueJsonConverter : JsonConverter
    {
        /// <summary>
        ///     To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)typeof(NFTMetadataAttributeValue).GetMethod("ToJson").Invoke(value, null));
        }

        /// <summary>
        ///     To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue,
            JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.String:
                    return new NFTMetadataAttributeValue(Convert.ToString(reader.Value));
                case JsonToken.Float:
                    return new NFTMetadataAttributeValue(Convert.ToDecimal(reader.Value));
                case JsonToken.Boolean:
                    return new NFTMetadataAttributeValue(Convert.ToBoolean(reader.Value));
                case JsonToken.StartObject:
                    return NFTMetadataAttributeValue.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return NFTMetadataAttributeValue.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        ///     Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }
}