/*
 * Indexer Search API
 *
 * This API implements endpoints to power data driven marketplace and game experiences
 *
 * The version of the OpenAPI document: 1.0
 * Contact: helpmebuild@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Search.Model
{
    /// <summary>
    ///     Search stacks result
    /// </summary>
    [DataContract(Name = "SearchStacksResult")]
    public class SearchStacksResult
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="SearchStacksResult" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SearchStacksResult()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="SearchStacksResult" /> class.
        /// </summary>
        /// <param name="result">List of stack bundles (required).</param>
        /// <param name="page">page (required).</param>
        public SearchStacksResult(List<StackBundle> result = default, Page page = default)
        {
            // to ensure "result" is required (not null)
            if (result == null)
                throw new ArgumentNullException(
                    "result is a required property for SearchStacksResult and cannot be null");
            Result = result;
            // to ensure "page" is required (not null)
            if (page == null)
                throw new ArgumentNullException(
                    "page is a required property for SearchStacksResult and cannot be null");
            Page = page;
        }

        /// <summary>
        ///     List of stack bundles
        /// </summary>
        /// <value>List of stack bundles</value>
        [DataMember(Name = "result", IsRequired = true, EmitDefaultValue = true)]
        public List<StackBundle> Result { get; set; }

        /// <summary>
        ///     Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", IsRequired = true, EmitDefaultValue = true)]
        public Page Page { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SearchStacksResult {\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}