/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Ts.Client.OpenAPIDateConverter;

namespace Immutable.Ts.Model
{
    /// <summary>
    /// CreateListingResBodyOrderStatusAnyOf2
    /// </summary>
    [DataContract(Name = "createListingResBodyOrderStatus_anyOf_2")]
    public partial class CreateListingResBodyOrderStatusAnyOf2
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatusAnyOf2" /> class.
        /// </summary>
        /// <param name="name">A terminal order status indicating that an order cannot be fulfilled due to expiry..</param>
        public CreateListingResBodyOrderStatusAnyOf2(string name = default(string))
        {
            this.Name = name;
        }

        /// <summary>
        /// A terminal order status indicating that an order cannot be fulfilled due to expiry.
        /// </summary>
        /// <value>A terminal order status indicating that an order cannot be fulfilled due to expiry.</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateListingResBodyOrderStatusAnyOf2 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
