/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Ts.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Immutable.Ts.Model
{
    /// <summary>
    /// The Order status
    /// </summary>
    [JsonConverter(typeof(CreateListingResBodyOrderStatusJsonConverter))]
    [DataContract(Name = "createListingResBodyOrderStatus")]
    public partial class CreateListingResBodyOrderStatus : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf1" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf1.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf1 actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf2" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf2.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf2 actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf3" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf3.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf3 actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf4" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf4.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf4 actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CreateListingResBodyOrderStatus" /> class
        /// with the <see cref="CreateListingResBodyOrderStatusAnyOf5" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of CreateListingResBodyOrderStatusAnyOf5.</param>
        public CreateListingResBodyOrderStatus(CreateListingResBodyOrderStatusAnyOf5 actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf1))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf2))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf3))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf4))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(CreateListingResBodyOrderStatusAnyOf5))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: CreateListingResBodyOrderStatusAnyOf, CreateListingResBodyOrderStatusAnyOf1, CreateListingResBodyOrderStatusAnyOf2, CreateListingResBodyOrderStatusAnyOf3, CreateListingResBodyOrderStatusAnyOf4, CreateListingResBodyOrderStatusAnyOf5");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf</returns>
        public CreateListingResBodyOrderStatusAnyOf GetCreateListingResBodyOrderStatusAnyOf()
        {
            return (CreateListingResBodyOrderStatusAnyOf)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf1`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf1`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf1</returns>
        public CreateListingResBodyOrderStatusAnyOf1 GetCreateListingResBodyOrderStatusAnyOf1()
        {
            return (CreateListingResBodyOrderStatusAnyOf1)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf2`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf2`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf2</returns>
        public CreateListingResBodyOrderStatusAnyOf2 GetCreateListingResBodyOrderStatusAnyOf2()
        {
            return (CreateListingResBodyOrderStatusAnyOf2)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf3`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf3`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf3</returns>
        public CreateListingResBodyOrderStatusAnyOf3 GetCreateListingResBodyOrderStatusAnyOf3()
        {
            return (CreateListingResBodyOrderStatusAnyOf3)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf4`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf4`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf4</returns>
        public CreateListingResBodyOrderStatusAnyOf4 GetCreateListingResBodyOrderStatusAnyOf4()
        {
            return (CreateListingResBodyOrderStatusAnyOf4)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `CreateListingResBodyOrderStatusAnyOf5`. If the actual instance is not `CreateListingResBodyOrderStatusAnyOf5`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of CreateListingResBodyOrderStatusAnyOf5</returns>
        public CreateListingResBodyOrderStatusAnyOf5 GetCreateListingResBodyOrderStatusAnyOf5()
        {
            return (CreateListingResBodyOrderStatusAnyOf5)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateListingResBodyOrderStatus {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, CreateListingResBodyOrderStatus.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CreateListingResBodyOrderStatus
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CreateListingResBodyOrderStatus</returns>
        public static CreateListingResBodyOrderStatus FromJson(string jsonString)
        {
            CreateListingResBodyOrderStatus newCreateListingResBodyOrderStatus = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCreateListingResBodyOrderStatus;
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf1>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf1: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf2>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf2: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf3>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf3: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf4>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf4: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newCreateListingResBodyOrderStatus = new CreateListingResBodyOrderStatus(JsonConvert.DeserializeObject<CreateListingResBodyOrderStatusAnyOf5>(jsonString, CreateListingResBodyOrderStatus.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newCreateListingResBodyOrderStatus;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into CreateListingResBodyOrderStatusAnyOf5: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

    }

    /// <summary>
    /// Custom JSON converter for CreateListingResBodyOrderStatus
    /// </summary>
    public class CreateListingResBodyOrderStatusJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CreateListingResBodyOrderStatus).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    return CreateListingResBodyOrderStatus.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return CreateListingResBodyOrderStatus.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
