/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Ts.Client.OpenAPIDateConverter;
using System.Reflection;

namespace Immutable.Ts.Model
{
    /// <summary>
    /// FulfillOrderResBodyOrderBuyInner
    /// </summary>
    [JsonConverter(typeof(FulfillOrderResBodyOrderBuyInnerJsonConverter))]
    [DataContract(Name = "fulfillOrderResBodyOrder_buy_inner")]
    public partial class FulfillOrderResBodyOrderBuyInner : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillOrderResBodyOrderBuyInner" /> class
        /// with the <see cref="FulfillOrderResBodyERC20Item" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FulfillOrderResBodyERC20Item.</param>
        public FulfillOrderResBodyOrderBuyInner(FulfillOrderResBodyERC20Item actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillOrderResBodyOrderBuyInner" /> class
        /// with the <see cref="FulfillOrderResBodyNativeItem" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of FulfillOrderResBodyNativeItem.</param>
        public FulfillOrderResBodyOrderBuyInner(FulfillOrderResBodyNativeItem actualInstance)
        {
            IsNullable = false;
            SchemaType = "anyOf";
            ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(FulfillOrderResBodyERC20Item))
                {
                    _actualInstance = value;
                }
                else if (value.GetType() == typeof(FulfillOrderResBodyNativeItem))
                {
                    _actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: FulfillOrderResBodyERC20Item, FulfillOrderResBodyNativeItem");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `FulfillOrderResBodyERC20Item`. If the actual instance is not `FulfillOrderResBodyERC20Item`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FulfillOrderResBodyERC20Item</returns>
        public FulfillOrderResBodyERC20Item GetFulfillOrderResBodyERC20Item()
        {
            return (FulfillOrderResBodyERC20Item)ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `FulfillOrderResBodyNativeItem`. If the actual instance is not `FulfillOrderResBodyNativeItem`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of FulfillOrderResBodyNativeItem</returns>
        public FulfillOrderResBodyNativeItem GetFulfillOrderResBodyNativeItem()
        {
            return (FulfillOrderResBodyNativeItem)ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FulfillOrderResBodyOrderBuyInner {\n");
            sb.Append("  ActualInstance: ").Append(ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(ActualInstance, FulfillOrderResBodyOrderBuyInner.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of FulfillOrderResBodyOrderBuyInner
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of FulfillOrderResBodyOrderBuyInner</returns>
        public static FulfillOrderResBodyOrderBuyInner FromJson(string jsonString)
        {
            FulfillOrderResBodyOrderBuyInner newFulfillOrderResBodyOrderBuyInner = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newFulfillOrderResBodyOrderBuyInner;
            }

            try
            {
                newFulfillOrderResBodyOrderBuyInner = new FulfillOrderResBodyOrderBuyInner(JsonConvert.DeserializeObject<FulfillOrderResBodyERC20Item>(jsonString, FulfillOrderResBodyOrderBuyInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newFulfillOrderResBodyOrderBuyInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FulfillOrderResBodyERC20Item: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newFulfillOrderResBodyOrderBuyInner = new FulfillOrderResBodyOrderBuyInner(JsonConvert.DeserializeObject<FulfillOrderResBodyNativeItem>(jsonString, FulfillOrderResBodyOrderBuyInner.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newFulfillOrderResBodyOrderBuyInner;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into FulfillOrderResBodyNativeItem: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

    }

    /// <summary>
    /// Custom JSON converter for FulfillOrderResBodyOrderBuyInner
    /// </summary>
    public class FulfillOrderResBodyOrderBuyInnerJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(FulfillOrderResBodyOrderBuyInner).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            switch (reader.TokenType)
            {
                case JsonToken.StartObject:
                    return FulfillOrderResBodyOrderBuyInner.FromJson(JObject.Load(reader).ToString(Formatting.None));
                case JsonToken.StartArray:
                    return FulfillOrderResBodyOrderBuyInner.FromJson(JArray.Load(reader).ToString(Formatting.None));
                default:
                    return null;
            }
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
