/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Ts.Client.OpenAPIDateConverter;

namespace Immutable.Ts.Model
{
    /// <summary>
    /// PrepareListingResBodySignableActionMessage
    /// </summary>
    [DataContract(Name = "prepareListingResBodySignableAction_message")]
    public partial class PrepareListingResBodySignableActionMessage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrepareListingResBodySignableActionMessage" /> class.
        /// </summary>
        /// <param name="domain">domain.</param>
        /// <param name="types">types.</param>
        /// <param name="value">value.</param>
        public PrepareListingResBodySignableActionMessage(PrepareListingResBodyTypedDataDomain domain = default(PrepareListingResBodyTypedDataDomain), Dictionary<string, List<PrepareListingResBodyRecordStringTypedDataFieldValueInner>> types = default(Dictionary<string, List<PrepareListingResBodyRecordStringTypedDataFieldValueInner>>), Dictionary<string, Object> value = default(Dictionary<string, Object>))
        {
            this.Domain = domain;
            this.Types = types;
            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets Domain
        /// </summary>
        [DataMember(Name = "domain", EmitDefaultValue = false)]
        public PrepareListingResBodyTypedDataDomain Domain { get; set; }

        /// <summary>
        /// Gets or Sets Types
        /// </summary>
        [DataMember(Name = "types", EmitDefaultValue = false)]
        public Dictionary<string, List<PrepareListingResBodyRecordStringTypedDataFieldValueInner>> Types { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public Dictionary<string, Object> Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PrepareListingResBodySignableActionMessage {\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
