/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Ts.Model
{
    /// <summary>
    ///     Response schema for the prepareOrderCancellations endpoint
    /// </summary>
    [DataContract(Name = "_v1_ts_sdk_orderbook_prepareOrderCancellations_post_200_response")]
    public class V1TsSdkOrderbookPrepareOrderCancellationsPost200Response
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="V1TsSdkOrderbookPrepareOrderCancellationsPost200Response" /> class.
        /// </summary>
        /// <param name="signableAction">signableAction.</param>
        public V1TsSdkOrderbookPrepareOrderCancellationsPost200Response(SignableAction signableAction = default)
        {
            SignableAction = signableAction;
        }

        /// <summary>
        ///     Gets or Sets SignableAction
        /// </summary>
        [DataMember(Name = "signableAction", EmitDefaultValue = false)]
        public SignableAction SignableAction { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1TsSdkOrderbookPrepareOrderCancellationsPost200Response {\n");
            sb.Append("  SignableAction: ").Append(SignableAction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}