/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Immutable.Ts.Model
{
    /// <summary>
    ///     V1TsSdkOrderbookCreateListingPostRequest
    /// </summary>
    [DataContract(Name = "_v1_ts_sdk_orderbook_createListing_post_request")]
    public class V1TsSdkOrderbookCreateListingPostRequest
    {
        /// <summary>
        ///     Initializes a new instance of the <see cref="V1TsSdkOrderbookCreateListingPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1TsSdkOrderbookCreateListingPostRequest()
        {
        }

        /// <summary>
        ///     Initializes a new instance of the <see cref="V1TsSdkOrderbookCreateListingPostRequest" /> class.
        /// </summary>
        /// <param name="makerFees">makerFees (required).</param>
        /// <param name="orderComponents">orderComponents (required).</param>
        /// <param name="orderHash">orderHash (required).</param>
        /// <param name="orderSignature">orderSignature (required).</param>
        public V1TsSdkOrderbookCreateListingPostRequest(List<FeeValue> makerFees = default,
            OrderComponents orderComponents = default, string orderHash = default, string orderSignature = default)
        {
            // to ensure "makerFees" is required (not null)
            if (makerFees == null)
                throw new ArgumentNullException(
                    "makerFees is a required property for V1TsSdkOrderbookCreateListingPostRequest and cannot be null");
            MakerFees = makerFees;
            // to ensure "orderComponents" is required (not null)
            if (orderComponents == null)
                throw new ArgumentNullException(
                    "orderComponents is a required property for V1TsSdkOrderbookCreateListingPostRequest and cannot be null");
            OrderComponents = orderComponents;
            // to ensure "orderHash" is required (not null)
            if (orderHash == null)
                throw new ArgumentNullException(
                    "orderHash is a required property for V1TsSdkOrderbookCreateListingPostRequest and cannot be null");
            OrderHash = orderHash;
            // to ensure "orderSignature" is required (not null)
            if (orderSignature == null)
                throw new ArgumentNullException(
                    "orderSignature is a required property for V1TsSdkOrderbookCreateListingPostRequest and cannot be null");
            OrderSignature = orderSignature;
        }

        /// <summary>
        ///     Gets or Sets MakerFees
        /// </summary>
        [DataMember(Name = "makerFees", IsRequired = true, EmitDefaultValue = true)]
        public List<FeeValue> MakerFees { get; set; }

        /// <summary>
        ///     Gets or Sets OrderComponents
        /// </summary>
        [DataMember(Name = "orderComponents", IsRequired = true, EmitDefaultValue = true)]
        public OrderComponents OrderComponents { get; set; }

        /// <summary>
        ///     Gets or Sets OrderHash
        /// </summary>
        [DataMember(Name = "orderHash", IsRequired = true, EmitDefaultValue = true)]
        public string OrderHash { get; set; }

        /// <summary>
        ///     Gets or Sets OrderSignature
        /// </summary>
        [DataMember(Name = "orderSignature", IsRequired = true, EmitDefaultValue = true)]
        public string OrderSignature { get; set; }

        /// <summary>
        ///     Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class V1TsSdkOrderbookCreateListingPostRequest {\n");
            sb.Append("  MakerFees: ").Append(MakerFees).Append("\n");
            sb.Append("  OrderComponents: ").Append(OrderComponents).Append("\n");
            sb.Append("  OrderHash: ").Append(OrderHash).Append("\n");
            sb.Append("  OrderSignature: ").Append(OrderSignature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        ///     Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }
    }
}