/*
 * TS SDK API
 *
 * running ts sdk as an api
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@immutable.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Immutable.Ts.Client.OpenAPIDateConverter;

namespace Immutable.Ts.Model
{
    /// <summary>
    /// V1TsSdkV1OrderbookCancelOrdersPostRequest
    /// </summary>
    [DataContract(Name = "_v1_ts_sdk_v1_orderbook_cancelOrders_post_request")]
    public partial class V1TsSdkV1OrderbookCancelOrdersPostRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TsSdkV1OrderbookCancelOrdersPostRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected V1TsSdkV1OrderbookCancelOrdersPostRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="V1TsSdkV1OrderbookCancelOrdersPostRequest" /> class.
        /// </summary>
        /// <param name="orderIds">orderIds (required).</param>
        /// <param name="accountAddress">accountAddress (required).</param>
        /// <param name="signature">signature (required).</param>
        public V1TsSdkV1OrderbookCancelOrdersPostRequest(List<string> orderIds = default(List<string>), string accountAddress = default(string), string signature = default(string))
        {
            // to ensure "orderIds" is required (not null)
            if (orderIds == null)
            {
                throw new ArgumentNullException("orderIds is a required property for V1TsSdkV1OrderbookCancelOrdersPostRequest and cannot be null");
            }
            this.OrderIds = orderIds;
            // to ensure "accountAddress" is required (not null)
            if (accountAddress == null)
            {
                throw new ArgumentNullException("accountAddress is a required property for V1TsSdkV1OrderbookCancelOrdersPostRequest and cannot be null");
            }
            this.AccountAddress = accountAddress;
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new ArgumentNullException("signature is a required property for V1TsSdkV1OrderbookCancelOrdersPostRequest and cannot be null");
            }
            this.Signature = signature;
        }

        /// <summary>
        /// Gets or Sets OrderIds
        /// </summary>
        [DataMember(Name = "orderIds", IsRequired = true, EmitDefaultValue = true)]
        public List<string> OrderIds { get; set; }

        /// <summary>
        /// Gets or Sets AccountAddress
        /// </summary>
        [DataMember(Name = "accountAddress", IsRequired = true, EmitDefaultValue = true)]
        public string AccountAddress { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name = "signature", IsRequired = true, EmitDefaultValue = true)]
        public string Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1TsSdkV1OrderbookCancelOrdersPostRequest {\n");
            sb.Append("  OrderIds: ").Append(OrderIds).Append("\n");
            sb.Append("  AccountAddress: ").Append(AccountAddress).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
