---
name: Lint contracts/

on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install packages for contracts
        working-directory: ./contracts
        run: rm yarn.lock && yarn install --network-concurrency 1
      - name: Run eslint against contracts
        working-directory: ./contracts
        run: yarn lint
