---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Lint Code Base

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

        ################################
        # Run Linter against code base #
        ################################
      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_MARKDOWN: false
          VALIDATE_GITLEAKS: false
          VALIDATE_JSCPD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false

        ##################################
        # Run eslint against json-server #
        ##################################
      - name: Install packages for json-server
        working-directory: ./json-server
        run: yarn install
      - name: Run eslint against json-server
        working-directory: ./json-server
        run: yarn lint

        ###################################
        # Run eslint against mint-backend #
        ###################################
      - name: Install packages for mint-backend
        working-directory: ./mint-backend
        run: yarn install
      - name: Run eslint against mint-backend
        working-directory: ./mint-backend
        run: yarn lint

        ################################
        # Run eslint against contracts #
        ################################
      - name: Install packages for contracts
        working-directory: ./contracts
        run: yarn install
      - name: Run eslint against contracts
        working-directory: ./contracts
        run: yarn lint
